import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("hrms", "routes/hrms.tsx"),
  route("hrms/employees", "routes/hrms.employees.tsx"),
    route("hrms/branding", "routes/hrms.branding.tsx"),
  route("hrms/employees/:id", "routes/hrms.employee.$id.tsx"),
  route("hrms/recruitment", "routes/hrms.recruitment.tsx"),
  route("hrms/onboarding", "routes/hrms.onboarding.tsx"),
  route("hrms/leave", "routes/hrms.leave.tsx"),
  route("hrms/attendance", "routes/hrms.attendance.tsx"),
  route("hrms/payroll", "routes/hrms.payroll.tsx"),
  route("hrms/expenses", "routes/hrms.expenses.tsx"),
  route("hrms/performance", "routes/hrms.performance.tsx"),
  route("hrms/learning", "routes/hrms.learning.tsx"),
  route("hrms/assets", "routes/hrms.assets.tsx"),
  route("hrms/exit", "routes/hrms.exit.tsx"),
  route("hrms/analytics", "routes/hrms.analytics.tsx"),
  route("hrms/hrbot", "routes/hrms.hrbot.tsx"),
  route("hrms/users", "routes/hrms.users.tsx"),
  route("hrms/profile/:userId", "routes/hrms.profile.$userId.tsx"),
  route("hrms/notifications", "routes/hrms.notifications.tsx"),
  route("hrms/settings", "routes/hrms.settings.tsx"),
  route("hrms/announcements", "routes/hrms.announcements.tsx"),
  route("hrms/shifts", "routes/hrms.shifts.tsx"),
  route("hrms/reports", "routes/hrms.reports.tsx"),
  route("hrms/setup", "routes/hrms.setup.tsx"),
  route("hrms/documents", "routes/hrms.documents.tsx"),
  route("hrms/it-declaration", "routes/hrms.it-declaration.tsx"),
  route("hrms/holidays", "routes/hrms.holidays.tsx"),
  route("hrms/resignation", "routes/hrms.resignation.tsx"),
  route("hrms/loans", "routes/hrms.loans.tsx"),
  route("hrms/fnf", "routes/hrms.fnf.tsx"),
  route("hrms/helpdesk", "routes/hrms.helpdesk.tsx"),
  route("hrms/offer-letters", "routes/hrms.offer-letters.tsx"),
  // ── Resource / API routes (used by useFetcher.load) ──────────────────────
  route("api/payroll/run-status", "routes/api.payroll.run-status.ts"),
] satisfies RouteConfig;
